PROJ20_G20_DOTNET/Controllers/AanwezigheidController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PROJ20_G20_DOTNET.Models.Domain;
using PROJ20_G20_DOTNET.Models.ViewModels;

namespace PROJ20_G20_DOTNET.Controllers
{
    [Authorize(Policy = "ViewAttendings")]
    public class AanwezigheidController : Controller
    {
        private ILidRepository _lidRepository;
        private IAanwezigheidRepository _aanwezigheidRepository;
        private IActiviteitRepository _activiteitRepository;
        private IInschrijvingRepository _inschrijvingRepository;
        private IActiviteitInschrijvingRepository _activiteitInschrijvingRepository;

        public AanwezigheidController(ILidRepository lidRepository, IAanwezigheidRepository aanwezigheidRepository,
            IActiviteitRepository activiteitRepository, IInschrijvingRepository inschrijvingRepository,
            IActiviteitInschrijvingRepository activiteitInschrijvingRepository)
        {
            _lidRepository = lidRepository;
            _aanwezigheidRepository = aanwezigheidRepository;
            _activiteitRepository = activiteitRepository;
            _inschrijvingRepository = inschrijvingRepository;
            _activiteitInschrijvingRepository = activiteitInschrijvingRepository;
        }

        public IActionResult Index()
        {
            IEnumerable<Activiteit> activiteiten 
                = _activiteitRepository
                .GetAll()
                .Where(ac => ac.BeginDatum > DateTime.Today.AddDays(-3) && DateTime.Today.AddDays(12) > ac.BeginDatum) //geeft enkel activiteiten +- 3 dagen == range van een week
                .OrderBy(ac => ac.BeginDatum)
                .ToList();
            if (activiteiten == null) {
                return NotFound();
            }
            ViewBag.Naam = "Naam";
            return View(activiteiten);
        }

        [HttpPost]
        public IActionResult Index(string BeginDatum, string EindDatum, string Naam, string submit) {
            string activiteitNaam = Naam ?? "";
            DateTime start, eind;
            if (BeginDatum == null) { start = DateTime.Today.AddDays(-3); } else { start = Convert.ToDateTime(BeginDatum); } // Als je niets ingeeft bij data zal hij de range tussen 1970(vaak gebruikte start defaultdate) en huidige datum + 50 jaar zetten
            if (EindDatum == null) { eind = DateTime.Today.AddDays(1000000); } else { eind = Convert.ToDateTime(EindDatum); }
            ViewData["NaamFilter"] = Naam;
            ViewData["Begindatum"] = BeginDatum;
            ViewData["Einddatum"] = EindDatum;
            IEnumerable<Activiteit> activiteiten = _activiteitRepository
                .GetAll()
                .Where(
                    ac => ac.BeginDatum >= start &&
                    ac.BeginDatum <= eind &&
                    ac.Naam.StartsWith(activiteitNaam, StringComparison.CurrentCultureIgnoreCase))
                .OrderBy(ac => ac.BeginDatum)
                .ToList();
            if (activiteiten == null) {
                return NotFound();
            }
            switch (submit) {
                case "Naam activiteit":
                    activiteiten = activiteiten.OrderBy(a => a.Naam).ToList();
                    ViewData["naamStyle"] = "visible";
                    break;
                case "Datum":
                    activiteiten = activiteiten.OrderBy(a => a.BeginDatum).ToList();
                    ViewData["begindatumStyle"] = "visible";
                    break;
                case "Tijdstip":
                    activiteiten = activiteiten.OrderBy(a => a.BeginDatum.TimeOfDay).ToList();
                    ViewData["einddatumStyle"] = "visible";
                    break;
                case "Formule":
                    activiteiten = activiteiten.OrderBy(a => a.Formule).ToList();
                    ViewData["fornuleStyle"] = "visible";
                    break;
                default:
                    activiteiten = activiteiten.OrderBy(a => a.BeginDatum).ToList();
                    break;
            }
            ViewBag.Naam = Naam;
            return View(activiteiten);
        }

        public IActionResult Aanwezigheden(int id)
        {
            Activiteit activiteit = _activiteitRepository.GetBy(id);
            if (activiteit == null) {
                return NotFound();
            }
            return View(activiteit);
        }

        [HttpPost]
        public IActionResult Aanwezigheden(int id, string Naam) {
            string naamFilter = Naam ?? "";
            Activiteit activiteit = _activiteitRepository.GetBy(id);
            if (activiteit == null) {
                return NotFound();
            }
            activiteit.ActiviteitInschrijvingen = activiteit.ActiviteitInschrijvingen
                .Where(
                    ai => ai.Inschrijving.Lid.Voornaam.StartsWith(naamFilter, StringComparison.CurrentCultureIgnoreCase) 
                    || ai.Inschrijving.Lid.Achternaam.StartsWith(naamFilter, StringComparison.CurrentCultureIgnoreCase))
                .ToList();
            ViewData["NaamFilter"] = naamFilter;
            return View(activiteit);
        }

        [HttpPost]
        public IActionResult VoegAanwezigheidToe(int id, int id2)
        {
            try {
                Lid lid = _lidRepository.GetBy(id2);
                if (lid == null) {
                    return NotFound();
                }
                Activiteit activiteit = _activiteitRepository.GetBy(id);
                if (activiteit == null) {
                    return NotFound();
                }
                ActiviteitInschrijving activiteitInschrijving =
                    activiteit.ActiviteitInschrijvingen.SingleOrDefault(ai => ai.ActiviteitId == id && ai.Inschrijving.Lid.Id == id2);
                activiteitInschrijving.IsAanwezig = true;
                Aanwezigheid aanwezigheid = new Aanwezigheid(lid, activiteit);
                _aanwezigheidRepository.Add(aanwezigheid);
                _aanwezigheidRepository.SaveChanges();
                TempData["Success"] = $"{lid.Voornaam} {lid.Achternaam} is succesvol aanwezig geplaatst!";
                return RedirectToAction(nameof(Aanwezigheden), activiteit);
            }
            catch (Exception ex) {
            }
            TempData["Error"] = "Aanwezig plaatsen is mislukt!";
            return View(nameof(Aanwezigheden), _activiteitRepository.GetBy(id));
        }
        [HttpPost]
        public IActionResult VerwijderAanwezigheid(int id, int id2) {
            try {
                Lid lid = _lidRepository.GetBy(id2);
                if (lid == null) {
                    return NotFound();
                }
                Activiteit activiteit = _activiteitRepository.GetBy(id);
                if (activiteit == null) {
                    return NotFound();
                }
                ActiviteitInschrijving activiteitInschrijving =
                    activiteit.ActiviteitInschrijvingen.SingleOrDefault(ai => ai.Activiteit.Id == id && ai.Inschrijving.Lid.Id == id2);
                activiteitInschrijving.IsAanwezig = false;
                Aanwezigheid aanwezigheid = _aanwezigheidRepository.GetAll().SingleOrDefault(aw => aw.Lid.Id == id2 && aw.Activiteit.Id == id);
                _aanwezigheidRepository.Delete(aanwezigheid);
                _aanwezigheidRepository.SaveChanges();
                TempData["Success"] = $"{lid.Voornaam} {lid.Achternaam} is succesvol afwezig geplaatst!";
                return RedirectToAction(nameof(Aanwezigheden), activiteit);
            } catch (Exception ex) {
            }
            TempData["Error"] = "Afwezig plaatsen is mislukt!";
            return View(nameof(Aanwezigheden), _activiteitRepository.GetBy(id));

        }
        [HttpPost]
        public IActionResult VoegGastToe(int id, AddGastOfProeflidViewModel viewModel) {
            try {
                Lid lid = new Lid(viewModel.Voornaam, viewModel.Achternaam, viewModel.Email, viewModel.Gsm, Functie.GAST);
                if(_lidRepository.GetByEmail(lid.Email) != null)
                {
                    int aantalAanwezigheden = _aanwezigheidRepository.GetAll().Where(a => a.Lid.Email == lid.Email).Count();
                    if (aantalAanwezigheden > 3)
                    {
                        TempData["Error"] = "Gast heeft al meer dan 3 aanwezigheden!";
                        return View(nameof(Aanwezigheden), _activiteitRepository.GetBy(id));
                    }
                }
                _lidRepository.Add(lid);
                _lidRepository.SaveChanges();

                Activiteit activiteit = _activiteitRepository.GetBy(id);
                Inschrijving inschrijving = new Inschrijving(lid, activiteit.Formule, DateTime.Now);
                _inschrijvingRepository.Add(inschrijving);
                _inschrijvingRepository.SaveChanges();
                ActiviteitInschrijving activiteitInschrijving = new ActiviteitInschrijving(activiteit, inschrijving);
                activiteitInschrijving.IsAanwezig = true;
                _activiteitInschrijvingRepository.Add(activiteitInschrijving);
                _activiteitInschrijvingRepository.SaveChanges();
                Aanwezigheid aanwezigheid = new Aanwezigheid(lid, activiteit);
                _aanwezigheidRepository.Add(aanwezigheid);
                _aanwezigheidRepository.SaveChanges();
                return RedirectToAction(nameof(Aanwezigheden), activiteit);
            } catch(Exception ex) { }
            TempData["Error"] = "Gast toevoegen is mislukt!";
            return View(nameof(Aanwezigheden), _activiteitRepository.GetBy(id));

        }
        public IActionResult NietIngeschrevenLeden(int id) {
            Activiteit activiteit = _activiteitRepository.GetBy(id);
            if (activiteit == null) {
                return NotFound();
            }

PROJ20_G20_DOTNET/Controllers/OefeningController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PROJ20_G20_DOTNET.Models.Domain;

namespace PROJ20_G20_DOTNET.Controllers {
    [Authorize(Policy = "ViewExercisesOwn")]
    public class OefeningController : Controller {
        private IOefeningRepository _oefeningRepository;
        private ILidRepository _lidRepository;
        private IRaadplegingRepository _raadplegingRepository;
        private UserManager<IdentityUser> _userManager;
        private SignInManager<IdentityUser> _signInManager;

        public OefeningController(IOefeningRepository oefeningRepository, ILidRepository lidRepository, IRaadplegingRepository raadplegingRepository,
            UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager) {
            _oefeningRepository = oefeningRepository;
            _lidRepository = lidRepository;
            _raadplegingRepository = raadplegingRepository;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public async Task<IActionResult> BepaalAdminLid() {
            IdentityUser signedInUser = await GetSignedInUserAsync();
            Lid lid = _lidRepository.GetAll().SingleOrDefault(l => l.Email.Equals(signedInUser.Email));
            if (lid == null) {
                return NotFound();
            }
            if (lid.Functie.Equals(Functie.BEHEERDER) || lid.Functie.Equals(Functie.TRAINER)) {
                return RedirectToAction(nameof(Leden));
            }
            return RedirectToAction(nameof(ToonOefeningenLid), new { id = lid.Id });
        }

        [Authorize(Policy = "ViewExercisesAllMembers")]
        public IActionResult Leden() {
            IEnumerable<Lid> leden = _lidRepository.GetAll();
            if (leden == null) {
                return NotFound();
            }
            return View(leden);
        }

        [HttpPost]
        public IActionResult Leden(string Naam) {
            string naamFilter = Naam ?? "";
            IEnumerable<Lid> leden = _lidRepository.GetAll()
                .Where(
                l => l.Voornaam.StartsWith(naamFilter, StringComparison.CurrentCultureIgnoreCase)
                || l.Achternaam.StartsWith(naamFilter, StringComparison.CurrentCultureIgnoreCase))
                .ToList();
            if (leden == null) {
                return NotFound();
            }
            ViewData["NaamFilter"] = naamFilter;
            return View(leden);
        }

        public IActionResult ToonOefeningenLid(int id) {
            Lid lid = _lidRepository.GetBy(id);
            if (lid == null) {
                return NotFound();
            }
            Graad graadLid = lid.Graad;

            IEnumerable<Oefening> oefeningen =
                _oefeningRepository.GetAll()
                .Where(oef => oef.Graad.CompareTo(graadLid) <= 0)
                .OrderByDescending(oef => oef.Graad)
                .ThenBy(oef => oef.Thema.Naam)
                .ThenBy(oef => oef.Titel)
                .ToList();

            ViewData["LidNaam"] = $"{lid.Voornaam} {lid.Achternaam}";
            ViewData["LidId"] = id;
            return View(oefeningen);
        }

        [HttpPost]
        public IActionResult ToonOefeningenLid(int id, string Naam) {
            string naamFilter = Naam ?? "";
            Lid lid = _lidRepository.GetBy(id);
            if (lid == null) {
                return NotFound();
            }

            Graad graad = lid.Graad;

            IEnumerable<Oefening> oefeningen = _oefeningRepository.GetAll()
                .Where(
                    o => o.Graad.CompareTo(graad) <= 0 &&
                    o.Titel.Contains(naamFilter, StringComparison.CurrentCultureIgnoreCase))
                .OrderByDescending(o => o.Graad)
                .ThenBy(o => o.Titel)
                .ToList();
            if (oefeningen == null) {
                return NotFound();
            }
            ViewData["NaamFilter"] = naamFilter;
            ViewData["LidNaam"] = $"{lid.Voornaam} {lid.Achternaam}";
            ViewData["LidId"] = id;
            return View(oefeningen);
        }

        public IActionResult RaadpleegOefening(int id, int id2) {
            //id = oefeningId | id2 = lidId
            Oefening oefening = _oefeningRepository.GetById(id);
            if (oefening == null) {
                return NotFound();
            }
            UpdateRaadpleging(id, id2);
            ViewData["LidId"] = id2;
            return View(oefening);
        }

        private void UpdateRaadpleging(int oefeningId, int lidId) {
            Raadpleging raadpleging = _raadplegingRepository.GetAll().SingleOrDefault(r => r.OefeningId == oefeningId && r.LidId == lidId);
            if (raadpleging != null) {
                raadpleging.AantalRaadplegingen++;
                raadpleging.VoegRaadplegingsTijdstipToe();
                _raadplegingRepository.SaveChanges();
            } else {
                Lid lid = _lidRepository.GetBy(lidId);
                Oefening oefening = _oefeningRepository.GetById(oefeningId);
                Raadpleging raadplegingNew = new Raadpleging(lid, oefening);
                raadplegingNew.AantalRaadplegingen++;
                raadplegingNew.VoegRaadplegingsTijdstipToe();
                _raadplegingRepository.Add(raadplegingNew);
                _raadplegingRepository.SaveChanges();
            }
        }

        #region User async methods
        private async Task<IdentityUser> GetSignedInUserAsync() {
            return await _userManager.GetUserAsync(HttpContext.User);
        }
        #endregion
    }
}

PROJ20_G20_DOTNET/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Taijitan Roshin Ryu</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        @*<link rel="stylesheet" href="~/lib/bootstrap-4.3.1-dist/css/bootstrap.css" />*@

        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/home.css" />
        <link rel="stylesheet" href="~/css/aanwezigheid.css" />
        <link rel="stylesheet" href="~/css/start.css" />
        <link rel="stylesheet" href="~/css/lidEditForm.css" />
        <link href="~/css/ledenOefening.css" rel="stylesheet" />
        <link href="~/css/ToonOefeningenLid.css" rel="stylesheet" />
        <link href="~/css/login.css" rel="stylesheet" />
        <link href="~/css/raadplegenOefening.css" rel="stylesheet" />
        <link href="~/css/indexLid.css" rel="stylesheet" />
        <link href="~/css/navBar.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

</head>
<body>
    @*<nav class="kleurNav navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand" style="color:white;">Taijitan Yoshin Ryu</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        @if ((await AuthorizationService.AuthorizeAsync(User, "Beheerder")).Succeeded ||
                           (await AuthorizationService.AuthorizeAsync(User, "Trainer")).Succeeded) {
                            <li><a asp-area="" asp-controller="Oefening" asp-action="BepaalAdminLid" style="color:white;">Lesmateriaal</a></li>
                            <li><a asp-area="" asp-controller="Aanwezigheid" asp-action="Index" style="color:white;">Aanwezigheid</a></li>
                        } else if ((await AuthorizationService.AuthorizeAsync(User, "Lid")).Succeeded ||
                          (await AuthorizationService.AuthorizeAsync(User, "Proeflid")).Succeeded ||
                          (await AuthorizationService.AuthorizeAsync(User, "Gast")).Succeeded) {
                            <li><a asp-area="" asp-controller="Oefening" asp-action="BepaalAdminLid" style="color:white;">Lesmateriaal</a></li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>*@

    <div class="cutomNavbarContainer">
        <div class="customNavbar">
            <div class="contentNavbar">
                <div class="navdiv">
                    <img class="navlogo" src="~/images/logo.png" />
                    <a class="navTitel" asp-controller="Home" asp-action="Index">Taijitan Yoshin Ryu</a>
                </div>
                <div class="grow"></div>
                <nav class="navLijst">
                    <ul class="lijst">
                        @if ((await AuthorizationService.AuthorizeAsync(User, "Beheerder")).Succeeded ||
(await AuthorizationService.AuthorizeAsync(User, "Trainer")).Succeeded) {
                    <li class="lijstItem @(ViewContext.RouteData.Values["Action"].ToString() == "Index" ? "active" : "")"><a class="navLink" asp-controller="Home" asp-action="Index">home</a></li>
                    <li class="lijstItem"><a class="navLink" asp-area="" asp-controller="Oefening" asp-action="BepaalAdminLid">Lesmateriaal</a></li>
                    <li class="lijstItem"><a class="navLink" asp-area="" asp-controller="Aanwezigheid" asp-action="Index">Aanwezigheden</a></li>

                } else if ((await AuthorizationService.AuthorizeAsync(User, "Lid")).Succeeded ||
                  (await AuthorizationService.AuthorizeAsync(User, "Proeflid")).Succeeded ||
                  (await AuthorizationService.AuthorizeAsync(User, "Gast")).Succeeded) {
                    <li class="lijstItem"><a class="navLink" asp-controller="Home" asp-action="Index">home</a></li>
                    <li class="lijstItem"><a class="navLink" asp-area="" asp-controller="Oefening" asp-action="BepaalAdminLid">Lesmateriaal</a></li>
                }
                    </ul>
                    <partial name="_LoginPartial" />
                </nav>
            </div>
        </div>
    </div>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="text-center">
            <p>&copy; 2019 - Taijitan Yoshin Ryu - All rights reserved.</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        @*<script src="~/lib/bootstrap-4.3.1-dist/js/bootstrap.js"></script>*@
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>